name: Weekly push

on:
  push:
  schedule:
    - cron: '45 23 * * 5'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
      PIXIV_REFRESH_TOKEN: ${{ secrets.PIXIV_REFRESH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Weekly push
        run: |
          python ./cmd.py --weekly
